# Generated by Django 5.1.1 on 2025-08-31 09:51

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('interests', models.TextField(blank=True, help_text='Comma-separated interests')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=accounts.models.user_avatar_path)),
                ('is_public', models.BooleanField(default=True)),
                ('friends', models.ManyToManyField(blank=True, to='accounts.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
