# Generated by Django 5.1.1 on 2025-09-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_public',
        ),
        migrations.AddField(
            model_name='profile',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends only'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
