# Generated by Django 5.1.1 on 2025-09-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_is_public_profile_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
    ]
