# Generated by Django 5.1.1 on 2025-09-15 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='testimonial_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
